name: city_builder
description: SimCity-inspired citybuilder built with Flutter & Flame.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.21.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  collection: ^1.18.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/tiles/
    - assets/sounds/
    - assets/fonts/
    - lib/l10n/app_de.arb
    - lib/l10n/app_en.arb
